package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Dotnet_Build1'
in the project with id = 'Dotnet', and delete the patch script.
*/
create(RelativeId("Dotnet"), BuildType({
    id("Dotnet_Build1")
    name = "build1"
}))

