package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Project1_HttpsGithubComChubatovaTigerDotNetTestsSamples'
in the project with id = 'Project1', and delete the patch script.
*/
create(RelativeId("Project1"), GitVcsRoot({
    id("Project1_HttpsGithubComChubatovaTigerDotNetTestsSamples")
    name = "https://github.com/ChubatovaTiger/DotNetTestsSamples"
    url = "https://github.com/ChubatovaTiger/DotNetTestsSamples"
    branch = "refs/heads/main"
    authMethod = password {
        userName = "ChubatovaTiger"
        password = "credentialsJSON:135526e3-a683-4f85-942f-ba049923d60b"
    }
}))

